fix: resolve database-compat to 2.1.6 to fix a regression in 2.1.5
It was actually requiring `@firebase/app` while declaring it as peer dependency,
leading to an "Error: Cannot find module '@firebase/app'" crash in deployed
Firebase Functions. We had the broken version installed due to `npmMinimalAgeGate: 7d`,

Locally, the module was found in the root front-end node_modules as a fallback.
Not remotely, because deploys only zip the api/ code.